---

- name: "Creating files and directories - Playbook"
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: "Create a file"
      file:
        path: /opt/dir1
        state: directory
        mode: 0755
        owner: ansadmin