---

- name: "Install multiple packages - Playbook"
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: "Installing packages"
      dnf:
        name: "{{ item.package }}"
        state: "{{ item.setup }}"
      loop:
        - { package: 'git', setup: 'installed' }
        - { package: 'make', setup: 'installed' }
        - { package: 'wget', setup: 'installed' }
        - { package: 'tree', setup: 'installed' }
        - { package: 'unzip', setup: 'installed' }
        - { package: 'tar', setup: 'installed' }